# Generated by Django 3.0.6 on 2020-05-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default='aaa123', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
