# Generated by Django 3.0.6 on 2020-05-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_auto_20200530_1530'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
